- id: doi:10.1038/s43018-022-00403-z
  type: paper
  description: 
  date:
  image: 
  buttons:
    - type: source
      text: Manuscript Source
      link: https://www.nature.com/articles/s43018-022-00403-z
  repo: FrankDubois/pHGG_SVs


